//! Autonomous strategy consults (SPEC-P20 §2–§3): pipeline triggers -> consult
//! task -> policy gate -> approved orders back to the pipeline; STRATEGY
//! journal entries.
//!
//! Every piece of this machinery is active only when a strategy engine exists
//! (`ENABLE_STRATEGY` plus a real provider key). With no engine the task is
//! inert and `main` does not spawn it — the pipeline keeps its pre-P20
//! behaviour byte-for-byte, and its `consult_scheduled` alerts for Yellow
//! entries are unchanged.
//!
//! ```text
//! pipeline --ConsultTrigger--> [consult task] --> StrategyEngine::consult
//!    ^                              |                     |
//!    |                       (audit-before-action)       v
//!    |   policy gate (Strategy) <-- Decision -> Intent mapping (bot parity)
//!    +--- ApprovedOrder (mpsc) <--- allow + sized order
//! ```
//!
//! Triggers (SPEC-P20 §2, per SPEC-P07 §5):
//!
//! - (a) Yellow-ENTRY transition per market — sent by the pipeline;
//! - (b) post-reflex review after an executed Orange/Red reduce — pipeline;
//! - (c) periodic portfolio review every `STRATEGY_REVIEW_INTERVAL_SECS`
//!   (default [`DEFAULT_REVIEW_INTERVAL_SECS`]) while any position is at or
//!   above Yellow — an internal timer delivered through the same handler as a
//!   [`ConsultTrigger::Periodic`] value.
//!
//! The strategy engine enforces the per-market rate limit and the hourly/daily
//! budget inside [`StrategyEngine::consult`]; a budget breach yields its
//! synthetic `ESCALATE` outcome, which this task journals and alerts like any
//! other ESCALATE. `NeedsApproval` decisions are journaled and alerted only —
//! the daemon path never shows an approval keyboard (the operator can re-run
//! `/risk` or `/close` by hand).
//!
//! Smart-money context is fetched cache-first through the P09 Nansen client
//! when one is configured (`NANSEN_PAYER_KEY` + `ENABLE_NANSEN`); any error or
//! timeout (capped at [`SM_FETCH_TIMEOUT`]) degrades to
//! [`SmartMoneyContext::unavailable`]. Without a client the context is
//! unavailable, silently.

use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use sentinel_core::audit::{
    AuditEntry, AuditJournal, IntentRecord, OutcomeRecord, Trigger, hash_input,
};
use sentinel_core::order::{OrderRequest, reduce_by_fraction};
use sentinel_core::policy::{DayState, PolicyConfig, PolicyContext, PolicyEngine, PolicySource};
use sentinel_core::risk::{self, RiskThresholds};
use sentinel_core::types::{
    AccountState, Decision, DecisionAction, ExecutionMode, Intent, Market, MarketId, PolicyVerdict,
    RiskTier,
};
use serde_json::{Value, json};
use tokio::sync::{Mutex, mpsc, watch};

use crate::bot::policy_admin::SharedPolicy;
use crate::brain::engine::{ConsultInput, ConsultOutcome, StrategyEngine};
use crate::brain::prompts::{PolicySummary, ReflexSummary, SmartMoneyContext};
use crate::brain::providers::Provider;
use crate::config::Config;
use crate::nansen::NansenClient;
use crate::notify::{Alert, AlertKind, AlertSink};
use crate::pipeline::LiveState;
use crate::reflex::REFLEX_SLIPPAGE_BPS;

/// Periodic portfolio-review cadence when `STRATEGY_REVIEW_INTERVAL_SECS` is
/// unset (seconds, SPEC-P20 §2c).
pub const DEFAULT_REVIEW_INTERVAL_SECS: u64 = 1800;

/// Hard cap on one smart-money fetch (SPEC-P20 §2.2): a slow paid call must
/// never stall the consult loop.
const SM_FETCH_TIMEOUT: Duration = Duration::from_secs(5);

/// Journal scan window used to summarise recent reflex actions.
const REFLEX_SCAN_LIMIT: usize = 500;

/// Maximum number of reflex actions rendered into the prompt summary.
const REFLEX_SUMMARY_LIMIT: usize = 6;

/// One reason the consult task should run a strategy consult.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConsultTrigger {
    /// A market just entered the Yellow tier (SPEC-P07 §5a).
    YellowEntry {
        /// Market that entered Yellow.
        market_id: MarketId,
    },
    /// A reflex reduce executed at Orange or Red; review the position
    /// (SPEC-P07 §5b).
    PostReflexReduce {
        /// Market the executed reduce targeted.
        market_id: MarketId,
        /// Tier at reflex-decision time (Orange or Red).
        tier: RiskTier,
    },
    /// Periodic portfolio review tick (SPEC-P20 §2c); generated by the
    /// consult task's own timer, never by the pipeline.
    Periodic,
}

impl ConsultTrigger {
    /// Stable label used in logs and journal documents.
    pub fn label(&self) -> &'static str {
        match self {
            ConsultTrigger::YellowEntry { .. } => "yellow_entry",
            ConsultTrigger::PostReflexReduce { .. } => "post_reflex_reduce",
            ConsultTrigger::Periodic => "periodic",
        }
    }
}

/// An allowed, sized strategy order travelling from the consult task to the
/// pipeline (SPEC-P20 §2.4). The pipeline submits it through its existing
/// executor/event/alert path and journals the STRATEGY outcome with the
/// execution status.
#[derive(Debug, Clone, PartialEq)]
pub struct ApprovedOrder {
    /// Consult decision correlation id (`s-<n>`).
    pub decision_id: String,
    /// Sized reduce-only order.
    pub order: OrderRequest,
}

/// The supervised consult task (one per daemon; built by `main`).
///
/// Generic over the engine's provider slots and the alert sink so tests can
/// drive it with mock providers and a recording sink.
pub struct ConsultTask<P: Provider, F: Provider, S> {
    /// Shared strategy engine (`None` makes the task inert).
    pub engine: Option<Arc<StrategyEngine<P, F>>>,
    /// Application configuration (policy summary source).
    pub cfg: Config,
    /// Shared live state (the same handle the pipeline maintains).
    pub state: Arc<Mutex<LiveState>>,
    /// Audit journal (`None` keeps the task journal-free, like the pipeline).
    pub journal: Option<Arc<Mutex<AuditJournal>>>,
    /// Policy overlay (kill switch + admin edits).
    pub policy: Arc<SharedPolicy>,
    /// Trigger channel from the pipeline. Shared so the supervised task can
    /// be rebuilt across restarts.
    pub triggers: Arc<Mutex<mpsc::Receiver<ConsultTrigger>>>,
    /// Approved orders toward the pipeline.
    pub orders: mpsc::Sender<ApprovedOrder>,
    /// Alert destination for consulted decisions.
    pub sink: S,
    /// Nansen client for smart-money enrichment (`None` degrades to
    /// [`SmartMoneyContext::unavailable`]).
    pub nansen: Option<Arc<NansenClient>>,
    /// Periodic review cadence, seconds (`STRATEGY_REVIEW_INTERVAL_SECS`).
    pub review_interval_secs: u64,
    /// Consult decision sequence (`s-<n>` correlation ids).
    seq: AtomicU64,
}

impl<P: Provider, F: Provider, S> ConsultTask<P, F, S> {
    /// Assemble a consult task over the shared daemon handles.
    #[allow(clippy::too_many_arguments)] // daemon wiring is explicit by design (SPEC-P20 §2)
    pub fn new(
        engine: Option<Arc<StrategyEngine<P, F>>>,
        cfg: Config,
        state: Arc<Mutex<LiveState>>,
        journal: Option<Arc<Mutex<AuditJournal>>>,
        policy: Arc<SharedPolicy>,
        triggers: Arc<Mutex<mpsc::Receiver<ConsultTrigger>>>,
        orders: mpsc::Sender<ApprovedOrder>,
        sink: S,
        nansen: Option<Arc<NansenClient>>,
        review_interval_secs: u64,
    ) -> Self {
        Self {
            engine,
            cfg,
            state,
            journal,
            policy,
            triggers,
            orders,
            sink,
            nansen,
            review_interval_secs,
            seq: AtomicU64::new(0),
        }
    }
}

impl<P, F, S> ConsultTask<P, F, S>
where
    P: Provider + Send + Sync + 'static,
    F: Provider + Send + Sync + 'static,
    S: AlertSink + Send + Sync + 'static,
{
    /// Run the consult loop until `shutdown` flips or the trigger channel
    /// closes. With no engine the task returns immediately (inert).
    pub async fn run(self, mut shutdown: watch::Receiver<bool>) {
        if self.engine.is_none() {
            tracing::info!("consult task inert (strategy engine unavailable)");
            return;
        }
        if *shutdown.borrow() {
            return;
        }
        let interval_secs = self.review_interval_secs.max(1);
        let interval = Duration::from_secs(interval_secs);
        let mut ticker = tokio::time::interval_at(tokio::time::Instant::now() + interval, interval);
        ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
        tracing::info!(review_interval_secs = interval_secs, "consult task started");

        loop {
            tokio::select! {
                biased;
                change = shutdown.changed() => {
                    if change.is_err() || *shutdown.borrow() {
                        break;
                    }
                }
                _ = ticker.tick() => {
                    self.handle_trigger(ConsultTrigger::Periodic).await;
                }
                trigger = next_trigger(&self.triggers) => {
                    match trigger {
                        Some(trigger) => self.handle_trigger(trigger).await,
                        None => {
                            tracing::info!("trigger channel closed; consult task stopping");
                            break;
                        }
                    }
                }
            }
        }
    }

    /// One trigger to completion: filter, build the input, journal the intent
    /// (audit-before-action), consult, then map -> gate -> act.
    async fn handle_trigger(&self, trigger: ConsultTrigger) {
        let now_ms = unix_ms();
        let Some((account, markets)) = self.snapshot().await else {
            tracing::debug!(
                trigger = trigger.label(),
                "consult skipped: no account snapshot yet"
            );
            return;
        };
        let thresholds = thresholds(&self.cfg);
        let Some(focus) = trigger_focus(&trigger, &account, &markets, &thresholds) else {
            tracing::debug!(
                trigger = trigger.label(),
                "consult skipped: trigger filtered out"
            );
            return;
        };
        let Some(engine) = &self.engine else {
            return;
        };
        let decision_id = self.next_decision_id();

        // Smart-money context (cache-first; degrade on any error/timeout).
        let asset = markets
            .iter()
            .find(|market| market.id == focus)
            .map(|market| market.symbol.clone())
            .unwrap_or_else(|| focus.0.to_string());
        let sm = self.smart_money(&asset, &chain_for(&asset)).await;

        let input = ConsultInput {
            account: account.clone(),
            markets: markets.clone(),
            focus_market: focus,
            policy: policy_summary(&self.cfg),
            sm,
            reflex: self.reflex_summary().await,
        };
        let input_hash = consult_input_hash(&input, &trigger, now_ms);

        // Audit-before-action (P00 invariant #2): the STRATEGY intent lands
        // before the consult call.
        self.journal_intent(&trigger, &input, &input_hash, &decision_id, now_ms)
            .await;

        let outcome = match engine.consult(&input, now_ms).await {
            Ok(outcome) => outcome,
            Err(err) => {
                tracing::warn!(
                    market_id = focus.0,
                    trigger = trigger.label(),
                    error = %err,
                    "strategy consult failed"
                );
                self.journal_outcome(
                    focus,
                    &input_hash,
                    json!({
                        "action": "consult",
                        "decision_id": decision_id,
                        "market_id": focus.0,
                        "trigger": trigger.label(),
                    }),
                    json!({ "verdict": "error" }),
                    json!({
                        "status": "error",
                        "error": err.to_string(),
                        "mode": mode_label(self.cfg.execution.mode),
                    }),
                    now_ms,
                )
                .await;
                return;
            }
        };
        self.act_on_outcome(&input, &input_hash, &decision_id, &outcome, now_ms)
            .await;
    }

    /// Map the decision to an [`Intent`], run the same policy gate the bot's
    /// `/risk` path uses (`PolicySource::Strategy`), and act:
    ///
    /// - allow + sized order -> send [`ApprovedOrder`] to the pipeline;
    /// - needs-approval / deny / escalate -> journal + alert only;
    /// - hold / no executable order -> journal (+ alert in Orange+).
    ///
    /// Every consulted decision in Orange+ alerts; needs-approval, deny and
    /// ESCALATE alert at any tier (SPEC-P20 §2.4–§2.5).
    async fn act_on_outcome(
        &self,
        input: &ConsultInput,
        input_hash: &str,
        decision_id: &str,
        outcome: &ConsultOutcome,
        now_ms: u64,
    ) {
        let decision = &outcome.decision;
        let market_id = MarketId(decision.market_id);
        let symbol = input
            .markets
            .iter()
            .find(|market| market.id == market_id)
            .map(|market| market.symbol.clone())
            .unwrap_or_else(|| market_id.0.to_string());
        let tier = tier_of(
            &input.account,
            &input.markets,
            market_id,
            &thresholds(&self.cfg),
        )
        .unwrap_or(RiskTier::Green);
        let action = action_label(decision.action);
        let decision_doc = consult_decision_json(decision_id, outcome);

        let (policy_verdict, execution, alert) = match decision.action {
            DecisionAction::Escalate => {
                let budget = outcome.provider_used == "budget";
                let status = if budget {
                    "escalate_budget"
                } else {
                    "escalate"
                };
                let text = format!(
                    "🧠 {}#{} strategy ESCALATE · {}",
                    symbol, market_id.0, decision.reason
                );
                (
                    json!({ "verdict": "escalate" }),
                    json!({
                        "status": status,
                        "mode": mode_label(self.cfg.execution.mode),
                        "budget_breach": budget,
                    }),
                    Some(strategy_alert(
                        market_id,
                        decision_id,
                        action,
                        status,
                        text,
                        now_ms,
                    )),
                )
            }
            DecisionAction::Hold => {
                let alert = (tier >= RiskTier::Orange).then(|| {
                    strategy_alert(
                        market_id,
                        decision_id,
                        action,
                        "hold",
                        format!(
                            "🧠 {}#{} strategy HOLD · {}",
                            symbol, market_id.0, decision.reason
                        ),
                        now_ms,
                    )
                });
                (
                    json!({ "verdict": "hold" }),
                    json!({ "status": "hold", "mode": mode_label(self.cfg.execution.mode) }),
                    alert,
                )
            }
            DecisionAction::Reduce | DecisionAction::Close | DecisionAction::AddCollateral => {
                self.gate_action(input, decision_id, decision, tier, &symbol, now_ms)
                    .await
            }
        };

        self.journal_outcome(
            market_id,
            input_hash,
            decision_doc,
            policy_verdict,
            execution,
            now_ms,
        )
        .await;
        if let Some(alert) = alert {
            self.send_alert(alert).await;
        }
    }

    /// The actionable half of [`Self::act_on_outcome`]: policy-gate the
    /// mapped intent and either queue an order or alert.
    #[allow(clippy::too_many_arguments)] // decision context is explicit by design (SPEC-P20 §2.4)
    async fn gate_action(
        &self,
        input: &ConsultInput,
        decision_id: &str,
        decision: &Decision,
        tier: RiskTier,
        symbol: &str,
        now_ms: u64,
    ) -> (Value, Value, Option<Alert>) {
        let market_id = MarketId(decision.market_id);
        let action = action_label(decision.action);
        let mode = mode_label(self.cfg.execution.mode);

        let Some(intent) = decision_intent(&input.account, decision) else {
            // Reduce against a missing/flat position (or missing amount): the
            // same "n/a" case the bot's `/risk` renders — nothing to gate.
            tracing::warn!(
                market_id = market_id.0,
                decision_id,
                "strategy decision has no resolvable intent; skipping the gate"
            );
            return (
                json!({ "verdict": "n/a" }),
                json!({ "status": "no_intent", "mode": mode }),
                None,
            );
        };

        let verdict = PolicyEngine::evaluate(
            &intent,
            &input.account,
            &policy_config(&self.cfg, self.policy.kill_switch()),
            &DayState { actions_today: 0 },
            &PolicyContext {
                source: PolicySource::Strategy,
                tier,
                market_id,
            },
        );
        let verdict_text_value = verdict_text(&verdict);
        let tier_text = tier_label(tier);

        match verdict {
            PolicyVerdict::Allow => {
                match size_order(&input.account, &input.markets, market_id, &intent) {
                    Some(order) => {
                        let order_doc = serde_json::to_value(&order).unwrap_or(Value::Null);
                        let size_text = order.size.to_string();
                        let approved = ApprovedOrder {
                            decision_id: decision_id.to_string(),
                            order,
                        };
                        match self.orders.send(approved).await {
                            Ok(()) => {
                                let alert = (tier >= RiskTier::Orange).then(|| {
                                    strategy_alert(
                                        market_id,
                                        decision_id,
                                        action,
                                        "allow: queued",
                                        format!(
                                            "🧠 {}#{} strategy {} · size {} queued for execution",
                                            symbol, market_id.0, action, size_text
                                        ),
                                        now_ms,
                                    )
                                });
                                (
                                    json!({ "verdict": verdict_text_value, "tier": tier_text, "order": order_doc }),
                                    json!({ "status": "queued", "mode": mode, "order": order_doc }),
                                    alert,
                                )
                            }
                            Err(err) => {
                                tracing::error!(
                                    market_id = market_id.0,
                                    error = %err,
                                    "strategy order channel closed; decision not queued"
                                );
                                (
                                    json!({ "verdict": verdict_text_value, "tier": tier_text, "order": order_doc }),
                                    json!({
                                        "status": "send_failed",
                                        "error": err.to_string(),
                                        "mode": mode,
                                    }),
                                    Some(strategy_alert(
                                        market_id,
                                        decision_id,
                                        action,
                                        "allow: send_failed",
                                        format!(
                                            "🧠 {}#{} strategy {} · order channel closed",
                                            symbol, market_id.0, action
                                        ),
                                        now_ms,
                                    )),
                                )
                            }
                        }
                    }
                    None => {
                        // AddCollateral has no pipeline path (orders are
                        // reduce-only) and a sizing miss means one lot/mark
                        // short — journal, alert in Orange+.
                        let alert = (tier >= RiskTier::Orange).then(|| {
                            strategy_alert(
                                market_id,
                                decision_id,
                                action,
                                "allow: no_order",
                                format!(
                                    "🧠 {}#{} strategy {} · no executable order (reduce-only pipeline)",
                                    symbol, market_id.0, action
                                ),
                                now_ms,
                            )
                        });
                        (
                            json!({ "verdict": verdict_text_value, "tier": tier_text, "order": Value::Null }),
                            json!({ "status": "no_order", "mode": mode }),
                            alert,
                        )
                    }
                }
            }
            PolicyVerdict::NeedsApproval { reason } => {
                // No keyboard from the daemon path (SPEC-P20 §2.4): journal +
                // alert only; the human can re-run `/risk` or `/close`.
                (
                    json!({ "verdict": verdict_text_value, "tier": tier_text, "reason": reason }),
                    json!({ "status": "needs_approval", "mode": mode }),
                    Some(strategy_alert(
                        market_id,
                        decision_id,
                        action,
                        "needs_approval",
                        format!(
                            "🧠 {}#{} strategy decision needs approval — use /approve or /risk · {}",
                            symbol, market_id.0, reason
                        ),
                        now_ms,
                    )),
                )
            }
            PolicyVerdict::Deny { reason } => (
                json!({ "verdict": verdict_text_value, "tier": tier_text, "reason": reason }),
                json!({ "status": "denied", "mode": mode }),
                Some(strategy_alert(
                    market_id,
                    decision_id,
                    action,
                    "deny",
                    format!(
                        "🧠 {}#{} strategy {} denied: {}",
                        symbol, market_id.0, action, reason
                    ),
                    now_ms,
                )),
            ),
        }
    }

    /// Live snapshot (account + markets), or `None` before the first account
    /// event.
    async fn snapshot(&self) -> Option<(AccountState, Vec<Market>)> {
        let state = self.state.lock().await;
        let account = state.account.clone()?;
        Some((account, state.markets.clone()))
    }

    /// Next consult correlation id (`s-<n>`).
    fn next_decision_id(&self) -> String {
        format!("s-{}", self.seq.fetch_add(1, Ordering::Relaxed) + 1)
    }

    /// Cache-first smart-money context for `asset` (SPEC-P20 §2.2).
    async fn smart_money(&self, asset: &str, chain: &str) -> SmartMoneyContext {
        let Some(client) = &self.nansen else {
            return SmartMoneyContext::unavailable(asset);
        };
        match tokio::time::timeout(
            SM_FETCH_TIMEOUT,
            client.smart_money_context(asset, chain, unix_ms()),
        )
        .await
        {
            Ok(context) => context,
            Err(_) => {
                tracing::warn!(
                    asset = %asset,
                    timeout_secs = SM_FETCH_TIMEOUT.as_secs(),
                    "smart-money fetch timed out; degrading to unavailable"
                );
                SmartMoneyContext::unavailable(asset)
            }
        }
    }

    /// Recent reflex actions from the journal (newest last).
    async fn reflex_summary(&self) -> ReflexSummary {
        let Some(journal) = &self.journal else {
            return ReflexSummary::default();
        };
        let entries = {
            let guard = journal.lock().await;
            match guard.read_entries(0, REFLEX_SCAN_LIMIT) {
                Ok(entries) => entries,
                Err(err) => {
                    tracing::warn!(error = %err, "reflex summary journal read failed");
                    return ReflexSummary::default();
                }
            }
        };
        reflex_summary_from(&entries, REFLEX_SUMMARY_LIMIT)
    }

    /// Journal one STRATEGY intent (audit-before-action).
    async fn journal_intent(
        &self,
        trigger: &ConsultTrigger,
        input: &ConsultInput,
        input_hash: &str,
        decision_id: &str,
        now_ms: u64,
    ) {
        let Some(journal) = &self.journal else {
            return;
        };
        let record = IntentRecord {
            trigger: Trigger::Strategy,
            account: account_label(&self.cfg),
            market_id: Some(input.focus_market.0),
            input_hash: input_hash.to_string(),
            decision: json!({
                "action": "consult",
                "decision_id": decision_id,
                "focus_market": input.focus_market.0,
                "trigger": trigger.label(),
                "policy": serde_json::to_value(&input.policy).unwrap_or(Value::Null),
            }),
            policy_verdict: json!({ "verdict": "pending", "note": "consult requested" }),
        };
        let mut guard = journal.lock().await;
        if let Err(err) = guard.record_intent(&record, journal_ts(now_ms)) {
            tracing::error!(
                error = %err,
                decision_id,
                "strategy intent journal write failed; proceeding"
            );
        }
    }

    /// Journal the STRATEGY outcome of one consult.
    async fn journal_outcome(
        &self,
        market_id: MarketId,
        input_hash: &str,
        decision: Value,
        policy_verdict: Value,
        execution: Value,
        now_ms: u64,
    ) {
        let Some(journal) = &self.journal else {
            return;
        };
        let record = OutcomeRecord {
            trigger: Trigger::Strategy,
            account: account_label(&self.cfg),
            market_id: Some(market_id.0),
            input_hash: input_hash.to_string(),
            decision,
            policy_verdict,
            execution,
        };
        let mut guard = journal.lock().await;
        if let Err(err) = guard.record_outcome(&record, journal_ts(now_ms)) {
            tracing::error!(error = %err, "strategy outcome journal write failed");
        }
    }

    /// Deliver one alert; failures are logged, never fatal.
    async fn send_alert(&self, alert: Alert) {
        if let Err(err) = self.sink.send(&alert).await {
            tracing::warn!(
                error = %err,
                market_id = alert.market_id.map(|market| market.0),
                "strategy alert delivery failed"
            );
        }
    }
}

/// Next trigger from the shared receiver (`None` once every sender dropped).
async fn next_trigger(triggers: &Mutex<mpsc::Receiver<ConsultTrigger>>) -> Option<ConsultTrigger> {
    triggers.lock().await.recv().await
}

/// Decision -> [`Intent`] mapping, identical to the bot `/risk` path
/// (SPEC-P20 §2.4): REDUCE scales by the consulted position's size, CLOSE and
/// ADD_COLLATERAL map directly (an amount is required), HOLD/ESCALATE produce
/// no intent, and a REDUCE against a missing or flat position resolves to
/// `None` (rendered as `n/a` by the bot).
pub(crate) fn decision_intent(account: &AccountState, decision: &Decision) -> Option<Intent> {
    let market_id = MarketId(decision.market_id);
    match decision.action {
        DecisionAction::Reduce => {
            let position = account
                .positions
                .iter()
                .find(|position| position.market_id == market_id)?;
            let amount = decision.amount?;
            if position.size.is_zero() {
                return None;
            }
            Some(Intent::Reduce {
                fraction: amount / position.size.abs(),
                reason: decision.reason.clone(),
            })
        }
        DecisionAction::Close => Some(Intent::Close {
            reason: decision.reason.clone(),
        }),
        DecisionAction::AddCollateral => {
            let amount = decision.amount?;
            Some(Intent::AddCollateral {
                amount,
                reason: decision.reason.clone(),
            })
        }
        DecisionAction::Hold | DecisionAction::Escalate => None,
    }
}

/// Resolve the consult focus for a trigger against the live snapshot; `None`
/// filters the trigger out (SPEC-P20 §2 trigger filtering).
fn trigger_focus(
    trigger: &ConsultTrigger,
    account: &AccountState,
    markets: &[Market],
    thresholds: &RiskThresholds,
) -> Option<MarketId> {
    match trigger {
        ConsultTrigger::YellowEntry { market_id } => {
            tier_of(account, markets, *market_id, thresholds).map(|_| *market_id)
        }
        ConsultTrigger::PostReflexReduce { market_id, tier } => {
            if *tier < RiskTier::Orange {
                return None;
            }
            tier_of(account, markets, *market_id, thresholds).map(|_| *market_id)
        }
        ConsultTrigger::Periodic => riskiest_at_or_above_yellow(account, markets, thresholds)
            .map(|(market_id, _)| market_id),
    }
}

/// Position tier for `market_id` against the snapshot, when derivable
/// (position and market both present, distance computable).
fn tier_of(
    account: &AccountState,
    markets: &[Market],
    market_id: MarketId,
    thresholds: &RiskThresholds,
) -> Option<RiskTier> {
    let position = account
        .positions
        .iter()
        .find(|position| position.market_id == market_id)?;
    let market = markets.iter().find(|market| market.id == market_id)?;
    risk::distance_to_liq_pct(position, market).map(|distance| risk::tier(distance, thresholds))
}

/// The riskiest position at or above Yellow (smallest distance first;
/// ties broken by market id for determinism).
fn riskiest_at_or_above_yellow(
    account: &AccountState,
    markets: &[Market],
    thresholds: &RiskThresholds,
) -> Option<(MarketId, RiskTier)> {
    account
        .positions
        .iter()
        .filter_map(|position| {
            let market = markets
                .iter()
                .find(|market| market.id == position.market_id)?;
            let distance = risk::distance_to_liq_pct(position, market)?;
            let tier = risk::tier(distance, thresholds);
            (tier >= RiskTier::Yellow).then_some((tier, distance, position.market_id))
        })
        .min_by(|left, right| left.1.cmp(&right.1).then_with(|| left.2.0.cmp(&right.2.0)))
        .map(|(tier, _, market_id)| (market_id, tier))
}

/// Size the reduce-only order for an allowed intent (same sizing and slippage
/// cap as the reflex engine and the bot's `/close`). `AddCollateral` has no
/// pipeline path and sizes to `None`.
fn size_order(
    account: &AccountState,
    markets: &[Market],
    market_id: MarketId,
    intent: &Intent,
) -> Option<OrderRequest> {
    let position = account
        .positions
        .iter()
        .find(|position| position.market_id == market_id)?;
    let market = markets.iter().find(|market| market.id == market_id)?;
    match intent {
        Intent::Reduce { fraction, .. } => {
            reduce_by_fraction(position, *fraction, market, REFLEX_SLIPPAGE_BPS)
        }
        Intent::Close { .. } => {
            reduce_by_fraction(position, Decimal::ONE, market, REFLEX_SLIPPAGE_BPS)
        }
        Intent::AddCollateral { .. } | Intent::Alert { .. } => None,
    }
}

/// Render recent reflex actions from journal entries (newest last, at most
/// `limit` lines). Non-reflex entries are ignored.
fn reflex_summary_from(entries: &[AuditEntry], limit: usize) -> ReflexSummary {
    let mut actions: Vec<String> = entries
        .iter()
        .filter(|entry| entry.trigger == Trigger::Reflex)
        .filter_map(reflex_action_line)
        .collect();
    if actions.len() > limit {
        actions.drain(..actions.len() - limit);
    }
    ReflexSummary { actions }
}

/// `d-<n> #<market> <action> · <status>` for one reflex journal entry.
fn reflex_action_line(entry: &AuditEntry) -> Option<String> {
    let decision_id = entry.decision.get("decision_id")?.as_str()?;
    let market_id = entry.market_id?;
    let action = entry
        .decision
        .get("action")
        .and_then(Value::as_str)
        .unwrap_or("action");
    let status = entry
        .execution
        .get("status")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    Some(format!("{decision_id} #{market_id} {action} · {status}"))
}

/// Canonical inputs hash for one consult (account snapshot + focus/trigger/
/// clock + the full prompt context).
fn consult_input_hash(input: &ConsultInput, trigger: &ConsultTrigger, now_ms: u64) -> String {
    let payload = json!({
        "account": serde_json::to_value(&input.account).unwrap_or(Value::Null),
        "focus_market": input.focus_market.0,
        "trigger": trigger.label(),
        "now_ms": now_ms,
        "policy": serde_json::to_value(&input.policy).unwrap_or(Value::Null),
        "sm": serde_json::to_value(&input.sm).unwrap_or(Value::Null),
        "reflex": serde_json::to_value(&input.reflex).unwrap_or(Value::Null),
    });
    hash_input(&[&payload])
}

/// Prompt-side policy summary (same mapping as the bot's `/risk`; the daily
/// count is the configured cap, documented approximation of SPEC-P11 §2).
fn policy_summary(cfg: &Config) -> PolicySummary {
    PolicySummary {
        market_allowlist: cfg
            .risk
            .market_allowlist
            .iter()
            .map(|id| MarketId(*id))
            .collect(),
        max_order_size_usd: cfg.risk.max_order_size_usd,
        require_approval_above_usd: cfg.risk.require_approval_above_usd,
        daily_actions_left: cfg.risk.max_daily_actions,
    }
}

/// Policy limits mapped from the effective configuration + overlay (identical
/// to the bot path).
fn policy_config(cfg: &Config, kill_switch: bool) -> PolicyConfig {
    PolicyConfig {
        market_allowlist: cfg
            .risk
            .market_allowlist
            .iter()
            .map(|id| MarketId(*id))
            .collect(),
        max_order_size_usd: cfg.risk.max_order_size_usd,
        max_daily_actions: cfg.risk.max_daily_actions,
        require_approval_above_usd: cfg.risk.require_approval_above_usd,
        kill_switch,
    }
}

/// Risk thresholds from the effective configuration.
fn thresholds(cfg: &Config) -> RiskThresholds {
    RiskThresholds {
        soft: cfg.risk.soft_pct,
        warn: cfg.risk.warn_pct,
        hard: cfg.risk.hard_pct,
    }
}

/// Rendered policy verdict (`allow` / `deny: …` / `needs_approval: …`).
fn verdict_text(verdict: &PolicyVerdict) -> String {
    match verdict {
        PolicyVerdict::Allow => "allow".to_string(),
        PolicyVerdict::Deny { reason } => format!("deny: {reason}"),
        PolicyVerdict::NeedsApproval { reason } => format!("needs_approval: {reason}"),
    }
}

/// Wire-style action label (`HOLD` … `ADD_COLLATERAL`).
fn action_label(action: DecisionAction) -> &'static str {
    match action {
        DecisionAction::Hold => "HOLD",
        DecisionAction::Reduce => "REDUCE",
        DecisionAction::Close => "CLOSE",
        DecisionAction::AddCollateral => "ADD_COLLATERAL",
        DecisionAction::Escalate => "ESCALATE",
    }
}

/// Uppercase tier name for journal documents.
fn tier_label(tier: RiskTier) -> &'static str {
    match tier {
        RiskTier::Green => "GREEN",
        RiskTier::Yellow => "YELLOW",
        RiskTier::Orange => "ORANGE",
        RiskTier::Red => "RED",
    }
}

/// Pipeline style mode label (`dry-run` / `testnet` / `mainnet`).
fn mode_label(mode: ExecutionMode) -> &'static str {
    match mode {
        ExecutionMode::DryRun => "dry-run",
        ExecutionMode::Testnet => "testnet",
        ExecutionMode::Mainnet => "mainnet",
    }
}

/// Full decision document for a consult outcome (audit context).
fn consult_decision_json(decision_id: &str, outcome: &ConsultOutcome) -> Value {
    json!({
        "action": action_label(outcome.decision.action),
        "decision_id": decision_id,
        "market_id": outcome.decision.market_id,
        "amount": outcome.decision.amount.map(|amount| amount.to_string()),
        "confidence": outcome.decision.confidence.to_string(),
        "urgency": format!("{:?}", outcome.decision.urgency).to_ascii_uppercase(),
        "reason": outcome.decision.reason.clone(),
        "provider": outcome.provider_used.clone(),
        "failover_from": outcome.failover_from.clone(),
        "prompt_version": outcome.prompt_version,
        "latency_ms": outcome.latency_ms,
        "repaired": outcome.repaired,
        "downgraded": outcome.downgraded,
        "source": "strategy_consult",
    })
}

/// Build one strategy-decision alert (SPEC-P20 §2.5).
fn strategy_alert(
    market_id: MarketId,
    decision_id: &str,
    action: &str,
    status: &str,
    text: String,
    at_ms: u64,
) -> Alert {
    Alert {
        kind: AlertKind::StrategyDecision {
            decision_id: decision_id.to_string(),
            action: action.to_string(),
            status: status.to_string(),
        },
        market_id: Some(market_id),
        text,
        at_ms,
    }
}

/// Account label for journal entries (same policy as the pipeline).
fn account_label(cfg: &Config) -> String {
    cfg.perpl
        .account
        .clone()
        .unwrap_or_else(|| "unknown".to_string())
}

/// Journal timestamp from the injected clock (wall clock as a fallback).
fn journal_ts(now_ms: u64) -> DateTime<Utc> {
    i64::try_from(now_ms)
        .ok()
        .and_then(DateTime::from_timestamp_millis)
        .unwrap_or_else(Utc::now)
}

/// Wall-clock milliseconds since the Unix epoch (0 before 1970).
fn unix_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|elapsed| u64::try_from(elapsed.as_millis()).unwrap_or(u64::MAX))
        .unwrap_or(0)
}

/// Best-effort Nansen chain name for a market symbol (cross-venue data
/// chains; the fallback is the lowercased symbol).
fn chain_for(symbol: &str) -> String {
    let uppercase = symbol.to_ascii_uppercase();
    match uppercase.as_str() {
        "ETH" | "WETH" => "ethereum".to_string(),
        "BTC" | "WBTC" => "bitcoin".to_string(),
        "SOL" => "solana".to_string(),
        "AVAX" => "avalanche".to_string(),
        "MON" => "monad".to_string(),
        _ => symbol.to_ascii_lowercase(),
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use rust_decimal::Decimal;
    use sentinel_core::audit::AuditEntry;
    use sentinel_core::order::CloseSide;
    use sentinel_core::types::{Position, Urgency};

    use super::*;
    use crate::brain::chain::NoProvider;
    use crate::brain::providers::MockProvider;
    use crate::notify::RecordingSink;
    use crate::perpl::{AccountEvent, FeedEvent};

    const NOW_MS: u64 = 1_764_500_000_000;

    fn dec(text: &str) -> Decimal {
        Decimal::from_str_exact(text).expect("valid decimal literal")
    }

    fn utc(ms: i64) -> DateTime<Utc> {
        DateTime::from_timestamp_millis(ms).expect("valid test timestamp")
    }

    /// ETH-like market: price 2dp, size 3dp, mmr 0.05, 12x max.
    fn eth_market() -> Market {
        Market {
            id: MarketId(32),
            symbol: "ETH".to_string(),
            base: "ETH Perp".to_string(),
            price_decimals: 2,
            size_decimals: 3,
            initial_margin_fraction: Decimal::from_str_exact("0.083333").expect("literal"),
            maintenance_margin_fraction: Decimal::from_str_exact("0.05").expect("literal"),
            max_leverage: dec("12"),
            min_size: Decimal::ZERO,
            tick_size: dec("0.01"),
            maker_fee_micros: 45,
            taker_fee_micros: 345,
            order_ttl_blocks: 20,
        }
    }

    /// BTC-like market on market 20 (mmr 0.05, size 3dp).
    fn btc_market() -> Market {
        Market {
            id: MarketId(20),
            symbol: "BTC".to_string(),
            base: "BTC Perp".to_string(),
            price_decimals: 2,
            size_decimals: 3,
            initial_margin_fraction: Decimal::from_str_exact("0.05").expect("literal"),
            maintenance_margin_fraction: Decimal::from_str_exact("0.05").expect("literal"),
            max_leverage: dec("20"),
            min_size: Decimal::ZERO,
            tick_size: dec("0.01"),
            maker_fee_micros: 45,
            taker_fee_micros: 345,
            order_ttl_blocks: 20,
        }
    }

    /// A long position with a collateral-derived liquidation distance.
    fn eth_position(size: &str, mark: &str, collateral: &str) -> Position {
        Position {
            market_id: MarketId(32),
            symbol: "ETH".to_string(),
            size: dec(size),
            entry_price: dec("2700.00"),
            mark_price: Some(dec(mark)),
            liq_price: None,
            collateral: dec(collateral),
            unrealized_pnl: (dec(mark) - dec("2700.00")) * dec(size),
            margin_ratio: None,
            leverage: dec("2"),
            opened_at: None,
        }
    }

    /// Account wrapping `positions`.
    fn account_of(positions: Vec<Position>) -> AccountState {
        AccountState {
            positions,
            free_balance: dec("1000"),
            equity: dec("1000"),
            fee_tier: 0,
            snapshot_ts: utc(NOW_MS as i64),
        }
    }

    /// A decision for the mapping tests.
    fn decision(action: DecisionAction, amount: Option<&str>) -> Decision {
        Decision {
            action,
            market_id: 32,
            amount: amount.map(dec),
            confidence: dec("0.7"),
            urgency: Urgency::Routine,
            reason: "mapping test".to_string(),
        }
    }

    fn thresholds() -> RiskThresholds {
        RiskThresholds {
            soft: dec("25"),
            warn: dec("15"),
            hard: dec("8"),
        }
    }

    fn test_config(extra: &[(&str, &str)]) -> Config {
        let mut vars: Vec<(String, String)> = [
            ("PERPL_ENV", "testnet"),
            ("PERPL_API_KEY", "test-api-key"),
            (
                "PERPL_API_KEY_SECRET",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
            ),
            ("QWEN_API_KEY", "test"),
            ("KIMI_API_KEY", "test"),
            ("NANSEN_PAYER_KEY", "0x11"),
            ("TELEGRAM_ALLOWED_USER_IDS", "1"),
            ("TELOXIDE_TOKEN", "test"),
            ("EXECUTION_MODE", "DRY_RUN"),
            ("MARKET_ALLOWLIST", "32"),
            ("MAX_ORDER_SIZE_USD", "100000"),
            ("REQUIRE_APPROVAL_ABOVE_USD", "100000"),
            ("REFLEX_COOLDOWN_SECS", "60"),
        ]
        .into_iter()
        .map(|(key, value)| (key.to_string(), value.to_string()))
        .collect();
        for (key, value) in extra {
            vars.push(((*key).to_string(), (*value).to_string()));
        }
        Config::from_vars(vars.into_iter().collect()).expect("test config")
    }

    fn shared_policy(dir: &Path) -> Arc<SharedPolicy> {
        Arc::new(SharedPolicy::load(dir.join("policy.json")))
    }

    fn fixture_state(position: Position) -> Arc<Mutex<LiveState>> {
        let mut live = LiveState::new();
        live.set_markets(vec![eth_market()]);
        let _ = live.apply(&FeedEvent::Account(AccountEvent::Snapshot {
            state: account_of(vec![position]),
        }));
        Arc::new(Mutex::new(live))
    }

    fn reduce_json(amount: &str) -> String {
        format!(
            r#"{{"action":"REDUCE","market_id":32,"amount":"{amount}","confidence":0.75,"urgency":"ROUTINE","reason":"trim into strength"}}"#
        )
    }

    /// Engine over a canned mock provider.
    fn mock_engine(
        responses: Vec<String>,
        min_interval_secs: u64,
    ) -> Arc<StrategyEngine<MockProvider, NoProvider>> {
        Arc::new(StrategyEngine::new(
            MockProvider::canned(responses),
            min_interval_secs,
            dec("0.6"),
        ))
    }

    // ---- decision -> Intent mapping (SPEC-P20 §2.4) -------------------------

    #[test]
    fn reduce_maps_to_its_fraction_of_the_position() {
        let account = account_of(vec![eth_position("10", "2500.00", "13560")]);
        let intent = decision_intent(&account, &decision(DecisionAction::Reduce, Some("2.5")));
        match intent {
            Some(Intent::Reduce { fraction, reason }) => {
                assert_eq!(fraction, dec("0.25"), "2.5 / 10");
                assert_eq!(reason, "mapping test");
            }
            other => panic!("expected a Reduce intent, got {other:?}"),
        }
    }

    #[test]
    fn reduce_against_missing_flat_position_or_missing_amount_is_none() {
        let account = account_of(vec![eth_position("10", "2500.00", "13560")]);
        assert_eq!(
            decision_intent(&account, &decision(DecisionAction::Reduce, None)),
            None,
            "a REDUCE without an amount cannot map"
        );
        let flat = account_of(vec![eth_position("0", "2500.00", "13560")]);
        assert_eq!(
            decision_intent(&flat, &decision(DecisionAction::Reduce, Some("1"))),
            None,
            "a flat position has no size to scale"
        );
        assert_eq!(
            decision_intent(
                &account_of(vec![]),
                &decision(DecisionAction::Reduce, Some("1"))
            ),
            None,
            "no position for the market resolves to n/a"
        );
    }

    #[test]
    fn close_and_add_collateral_map_and_hold_escalate_do_not() {
        let account = account_of(vec![eth_position("10", "2500.00", "13560")]);
        assert_eq!(
            decision_intent(&account, &decision(DecisionAction::Close, None)),
            Some(Intent::Close {
                reason: "mapping test".to_string()
            })
        );
        assert_eq!(
            decision_intent(
                &account,
                &decision(DecisionAction::AddCollateral, Some("300"))
            ),
            Some(Intent::AddCollateral {
                amount: dec("300"),
                reason: "mapping test".to_string()
            })
        );
        assert_eq!(
            decision_intent(&account, &decision(DecisionAction::AddCollateral, None)),
            None,
            "ADD_COLLATERAL without an amount has nothing to add"
        );
        assert_eq!(
            decision_intent(&account, &decision(DecisionAction::Hold, None)),
            None
        );
        assert_eq!(
            decision_intent(&account, &decision(DecisionAction::Escalate, None)),
            None
        );
    }

    // ---- trigger filtering (SPEC-P20 §2) -------------------------------------

    #[test]
    fn yellow_entry_requires_a_live_position_for_that_market() {
        let account = account_of(vec![eth_position("10", "2500.00", "13560")]);
        let markets = vec![eth_market()];
        let thresholds = thresholds();
        assert_eq!(
            trigger_focus(
                &ConsultTrigger::YellowEntry {
                    market_id: MarketId(32)
                },
                &account,
                &markets,
                &thresholds
            ),
            Some(MarketId(32))
        );
        assert_eq!(
            trigger_focus(
                &ConsultTrigger::YellowEntry {
                    market_id: MarketId(99)
                },
                &account,
                &markets,
                &thresholds
            ),
            None,
            "a closed/unknown market filters the trigger out"
        );
    }

    #[test]
    fn post_reflex_review_requires_orange_or_red() {
        let account = account_of(vec![eth_position("10", "2500.00", "13560")]);
        let markets = vec![eth_market()];
        let thresholds = thresholds();
        for tier in [RiskTier::Orange, RiskTier::Red] {
            assert_eq!(
                trigger_focus(
                    &ConsultTrigger::PostReflexReduce {
                        market_id: MarketId(32),
                        tier
                    },
                    &account,
                    &markets,
                    &thresholds
                ),
                Some(MarketId(32))
            );
        }
        assert_eq!(
            trigger_focus(
                &ConsultTrigger::PostReflexReduce {
                    market_id: MarketId(32),
                    tier: RiskTier::Yellow
                },
                &account,
                &markets,
                &thresholds
            ),
            None,
            "below Orange the pipeline never sends this trigger; filter defensively"
        );
        assert_eq!(
            trigger_focus(
                &ConsultTrigger::PostReflexReduce {
                    market_id: MarketId(99),
                    tier: RiskTier::Red
                },
                &account,
                &markets,
                &thresholds
            ),
            None
        );
    }

    #[test]
    fn periodic_review_focuses_the_riskiest_position_at_or_above_yellow() {
        let markets = vec![eth_market(), btc_market()];
        let thresholds = thresholds();

        // All Green (far from liquidation): no review.
        let green = account_of(vec![eth_position("10", "2500.00", "13560")]);
        assert_eq!(
            trigger_focus(&ConsultTrigger::Periodic, &green, &markets, &thresholds),
            None
        );

        // One Yellow (ETH ~22.2%), one Orange (BTC ~10.9%): the Orange wins.
        let orange = Position {
            market_id: MarketId(20),
            symbol: "BTC".to_string(),
            size: dec("1"),
            entry_price: dec("30000.00"),
            mark_price: Some(dec("32000.00")),
            liq_price: None,
            collateral: dec("3000"),
            unrealized_pnl: dec("2000"),
            margin_ratio: None,
            leverage: dec("10"),
            opened_at: None,
        };
        let mixed = account_of(vec![eth_position("10", "1900.00", "13560"), orange.clone()]);
        let focus = trigger_focus(&ConsultTrigger::Periodic, &mixed, &markets, &thresholds);
        assert_eq!(
            focus,
            Some(MarketId(20)),
            "the riskiest (Orange) position is reviewed first"
        );

        // Skip positions whose market is not in the snapshot (and never
        // fail the review for the remaining Yellow position).
        let unknown = Position {
            market_id: MarketId(77),
            ..orange
        };
        let with_unknown = account_of(vec![eth_position("10", "1900.00", "13560"), unknown]);
        assert_eq!(
            trigger_focus(
                &ConsultTrigger::Periodic,
                &with_unknown,
                &markets,
                &thresholds
            ),
            Some(MarketId(32)),
            "positions without a market row are skipped"
        );
    }

    // ---- reflex summary rendering -------------------------------------------

    fn reflex_entry(
        seq: u64,
        market_id: u32,
        id: &str,
        action: &str,
        status: &str,
        go: bool,
    ) -> AuditEntry {
        AuditEntry::new(
            seq,
            utc(NOW_MS as i64),
            if go {
                Trigger::Reflex
            } else {
                Trigger::Strategy
            },
            "0xacct".to_string(),
            Some(market_id),
            "hash".to_string(),
            json!({ "decision_id": id, "action": action }),
            json!({}),
            json!({ "status": status }),
            sentinel_core::audit::GENESIS_PREV_HASH.to_string(),
        )
    }

    #[test]
    fn reflex_summary_keeps_the_newest_actions_of_the_limit() {
        let entries = vec![
            reflex_entry(1, 32, "d-1", "reduce 25%", "simulated", true),
            reflex_entry(2, 32, "d-2", "none", "skipped", false),
            reflex_entry(3, 20, "d-3", "close", "submitted", true),
            reflex_entry(4, 20, "d-4", "reduce 10%", "simulated", true),
        ];
        let summary = reflex_summary_from(&entries, 2);
        assert_eq!(
            summary.actions,
            vec![
                "d-3 #20 close · submitted".to_string(),
                "d-4 #20 reduce 10% · simulated".to_string(),
            ],
            "newest last, non-reflex entries and the tail cut left out"
        );
    }

    // ---- engine-None inertness & SM degradation ------------------------------

    #[tokio::test]
    async fn task_with_no_engine_is_inert_and_consults_nothing() {
        let dir = tempfile::tempdir().expect("tempdir");
        let (trigger_tx, trigger_rx) = mpsc::channel(4);
        let (order_tx, mut order_rx) = mpsc::channel(4);
        let task = ConsultTask::<MockProvider, NoProvider, RecordingSink>::new(
            None,
            test_config(&[]),
            fixture_state(eth_position("10", "2500.00", "13560")),
            None,
            shared_policy(dir.path()),
            Arc::new(Mutex::new(trigger_rx)),
            order_tx,
            RecordingSink::new(),
            None,
            3600,
        );
        trigger_tx
            .send(ConsultTrigger::YellowEntry {
                market_id: MarketId(32),
            })
            .await
            .expect("queue a trigger");
        let (_shutdown_tx, shutdown_rx) = watch::channel(false);
        let joined = tokio::time::timeout(Duration::from_secs(2), task.run(shutdown_rx)).await;
        assert!(joined.is_ok(), "engine-None run returns immediately");
        assert!(order_rx.try_recv().is_err(), "no consult, no order");
    }

    #[tokio::test]
    async fn smart_money_without_a_client_is_unavailable() {
        let dir = tempfile::tempdir().expect("tempdir");
        let (_trigger_tx, trigger_rx) = mpsc::channel(4);
        let (order_tx, _order_rx) = mpsc::channel(4);
        let task = ConsultTask::<MockProvider, NoProvider, RecordingSink>::new(
            None,
            test_config(&[]),
            fixture_state(eth_position("10", "2500.00", "13560")),
            None,
            shared_policy(dir.path()),
            Arc::new(Mutex::new(trigger_rx)),
            order_tx,
            RecordingSink::new(),
            None,
            3600,
        );
        assert_eq!(
            task.smart_money("ETH", "ethereum").await,
            SmartMoneyContext::unavailable("ETH"),
            "no payer key ⇒ unavailable, no warning spam"
        );
    }

    // ---- one full allow cycle (trigger -> consult -> gate -> order) ----------

    #[tokio::test]
    async fn yellow_entry_consult_queues_a_policy_allowed_order_and_journals() {
        let dir = tempfile::tempdir().expect("tempdir");
        let journal = AuditJournal::open(dir.path().join("audit")).expect("open journal");
        let journal = Arc::new(Mutex::new(journal));
        let (trigger_tx, trigger_rx) = mpsc::channel(4);
        let (order_tx, mut order_rx) = mpsc::channel(4);
        let sink = RecordingSink::new();
        let alerts = Arc::clone(&sink.alerts);
        let task = ConsultTask::<MockProvider, NoProvider, RecordingSink>::new(
            Some(mock_engine(vec![reduce_json("1.0")], 0)),
            test_config(&[]),
            fixture_state(eth_position("10", "2500.00", "13560")),
            Some(Arc::clone(&journal)),
            shared_policy(dir.path()),
            Arc::new(Mutex::new(trigger_rx)),
            order_tx,
            sink,
            None,
            3600,
        );
        let (shutdown_tx, shutdown_rx) = watch::channel(false);
        let handle = tokio::spawn(task.run(shutdown_rx));

        trigger_tx
            .send(ConsultTrigger::YellowEntry {
                market_id: MarketId(32),
            })
            .await
            .expect("queue a trigger");

        let approved = tokio::time::timeout(Duration::from_secs(5), order_rx.recv())
            .await
            .expect("an order within the timeout")
            .expect("the channel stays open");
        assert_eq!(approved.decision_id, "s-1");
        assert_eq!(approved.order.market_id, MarketId(32));
        assert_eq!(approved.order.close, CloseSide::CloseLong);
        assert_eq!(approved.order.size, dec("1.000"), "0.1 × 10 quantized");

        // Shutdown and join so every journal write has landed.
        shutdown_tx.send(true).expect("shutdown");
        tokio::time::timeout(Duration::from_secs(5), handle)
            .await
            .expect("task stops")
            .expect("no panic");

        let entries = journal
            .lock()
            .await
            .read_entries(0, 10)
            .expect("read journal");
        assert_eq!(entries.len(), 2, "intent before, outcome after");
        assert_eq!(entries[0].trigger, Trigger::Strategy);
        assert_eq!(entries[0].execution["status"], "pending");
        assert_eq!(entries[0].decision["action"], "consult");
        assert_eq!(entries[1].trigger, Trigger::Strategy);
        assert_eq!(entries[1].execution["status"], "queued");
        assert_eq!(entries[1].policy_verdict["verdict"], "allow");
        assert_eq!(entries[1].decision["decision_id"], "s-1");
        assert!(
            alerts.lock().expect("alerts lock").is_empty(),
            "no alert for a quiet Yellow allow"
        );
    }

    #[tokio::test]
    async fn needs_approval_decision_alerts_without_an_order() {
        let dir = tempfile::tempdir().expect("tempdir");
        let (trigger_tx, trigger_rx) = mpsc::channel(4);
        let (order_tx, mut order_rx) = mpsc::channel(4);
        let sink = RecordingSink::new();
        let alerts = Arc::clone(&sink.alerts);
        let task = ConsultTask::<MockProvider, NoProvider, RecordingSink>::new(
            Some(mock_engine(vec![reduce_json("1.0")], 0)),
            // Approval threshold below the 2500 USD notional forces NeedsApproval.
            test_config(&[("REQUIRE_APPROVAL_ABOVE_USD", "100")]),
            fixture_state(eth_position("10", "2500.00", "13560")),
            None,
            shared_policy(dir.path()),
            Arc::new(Mutex::new(trigger_rx)),
            order_tx,
            sink,
            None,
            3600,
        );
        let (shutdown_tx, shutdown_rx) = watch::channel(false);
        let handle = tokio::spawn(task.run(shutdown_rx));

        trigger_tx
            .send(ConsultTrigger::YellowEntry {
                market_id: MarketId(32),
            })
            .await
            .expect("queue a trigger");

        // Poll for the alert, then stop the task.
        let mut captured = Vec::new();
        for _ in 0..50 {
            captured = alerts.lock().expect("alerts lock").clone();
            if !captured.is_empty() {
                break;
            }
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
        assert_eq!(captured.len(), 1, "one alert for the needs-approval case");
        assert!(captured[0].text.contains("needs approval"));
        assert!(
            matches!(&captured[0].kind, AlertKind::StrategyDecision { .. }),
            "alert kind: {:?}",
            captured[0].kind
        );
        assert_eq!(captured[0].market_id, Some(MarketId(32)));
        assert!(order_rx.try_recv().is_err(), "no keyboard, no order");

        shutdown_tx.send(true).expect("shutdown");
        tokio::time::timeout(Duration::from_secs(5), handle)
            .await
            .expect("task stops")
            .expect("no panic");
    }
}
